- name: Install Nginx on Web Server
  hosts: all
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy HTML file to Nginx web directory
      copy:
        src: index.html
        dest: /var/www/html/index.html
