- name: Install multiple packages
  hosts: all
  become: true

  tasks:
    - name: Install packages using loop
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - wget
        - tree
        - curl
